import setuptools
conf = setuptools.config.read_configuration('./setup.cfg')
meta=conf['metadata']
setuptools.setup( name=meta['name'],
                  version=meta['version'],
                  author=meta['author'],
                  author_email=meta['author_email'],
                  description=meta['description'],
                  long_description=meta['long_description'],
                  long_description_content_type="text/markdown",
                  url=meta['url'],
                  packages=setuptools.find_packages(),
                  setup_requires=['cython'],
                  install_requires=[ 'numpy',
                                     'matplotlib',
                                     'netCDF4',
                                     'scipy',
                                     'haversine',
                                     'pyproj',
                                     'wget',
                                     'utm',
                                     'requests',
                                     'tqdm',
                                     'eventlet',
                                     'paramiko_expect',
                                     'bs4'],
                  test_suite='nose.collector',
                  tests_require=['nose'])