#! /usr/bin/env python
import sys
sys.path.append('..')
import os
import argparse
import matplotlib.pyplot as plt
from AdcircPy import AdcircPy
from AdcircPy.core.Validation import COOPS

cwd = os.getcwd()

def _parse_args():
    global args
    parser = argparse.ArgumentParser(description="Program to see a quick plot of an ADCIRC mesh.")
    parser.add_argument("fort61", help="Path to ADCIRC fort.61 or fort.61.nc file.")    
    args =  parser.parse_args()

def main():
    _parse_args()
    AdcStations = AdcircPy.read_output(args.fort61)
    coops       = COOPS.from_station_list(list(AdcStations.keys()), AdcStations.time[0], AdcStations.time[-1])
    for station in AdcStations.keys():
        plt.plot(coops[station]['time'], coops[station]['zeta'])
        plt.plot(AdcStations.time, AdcStations[station]['zeta'])
        plt.gca().set_title(coops[station]['metadata']['name'])
        plt.show()


if __name__ == "__main__":
    main()