#! /usr/bin/env python
import os
import argparse
import matplotlib.pyplot as plt
from AdcircPy import Mesh

cwd = os.getcwd()

def parse_args():
    global args
    parser = argparse.ArgumentParser(description="Program to see a quick plot of an ADCIRC mesh.")
    parser.add_argument("meshPath", nargs="?", default = cwd + "/fort.14", help="ADCIRC mesh file path. Defaults to ./fort.14")    
    args =  parser.parse_args()
    
def main():
    parse_args()
    mesh = Mesh.init_from_files(args.meshPath)
    mesh.make_plot()
    plt.show()

if __name__ == "__main__":
    main()