#!/bin/bash --login
#SBATCH -D .
#SBATCH -J AdcircPy/examples/example_3.py
#SBATCH -A account
#SBATCH --mail-type=all
#SBATCH --mail-user=example@email.gov
#SBATCH --output=example_3.log
#SBATCH -n 1000
#SBATCH --time=08:00:00
#SBATCH --partition=partition

set -e

module load intel/2020 impi/2020 netcdf/4.7.2-parallel

PATH=$HOME/adcirc/build:$PATH

main() {
  SECONDS=0
  run_coldstart_phase
  if grep -Rq "ERROR: Elevation.gt.ErrorElev, ADCIRC stopping." example_3.log; then
    duration=$SECONDS
    echo "ERROR: Elevation.gt.ErrorElev, ADCIRC stopping."
    echo "Wallclock time: $(($duration / 60)) minutes and $(($duration % 60)) seconds."
    exit -1
  else
    run_hotstart_phase
    duration=$SECONDS
    if grep -Rq "ERROR: Elevation.gt.ErrorElev, ADCIRC stopping." example_3.log; then
      echo "ERROR: Elevation.gt.ErrorElev, ADCIRC stopping."
      echo "Wallclock time: $(($duration / 60)) minutes and $(($duration % 60)) seconds."
      exit -1
    fi
  fi
  echo "Wallclock time: $(($duration / 60)) minutes and $(($duration % 60)) seconds."
}

run_coldstart_phase() {
  rm -rf coldstart
  mkdir coldstart
  cd coldstart
  ln -sf ../fort.14
  ln -sf ../fort.13
  ln -sf ../fort.15.coldstart ./fort.15
  adcprep --np $SLURM_NTASKS --partmesh
  adcprep --np $SLURM_NTASKS --prepall
  srun padcirc clean_directory
  cd ..
}

run_hotstart_phase() {
  rm -rf hotstart
  mkdir hotstart
  cd hotstart
  ln -sf ../fort.14
  ln -sf ../fort.13
  ln -sf ../fort.15.hotstart ./fort.15
  ln -sf ../coldstart/fort.67.nc
  adcprep --np $SLURM_NTASKS --partmesh
  adcprep --np $SLURM_NTASKS --prepall
  srun padcirc clean_directory
  cd ..
}

clean_directory() {
  rm -rf PE*
  rm -rf partmesh.txt
  rm -rf metis_graph.txt
  rm -rf fort.13
  rm -rf fort.14
  rm -rf fort.15
  rm -rf fort.16
  rm -rf fort.80
  rm -rf fort.68.nc
}

main
